
# WE have tag the image old to new or dev to prod
name: CDPROD with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker Image
    # we are using the Pipe for multi line code/script
      run: |
          docker pull ybipin/devtaskmaster:latest
          docker tag ybipin/devtaskmaster:latest ybipin/prodtaskmaster:latest 
          docker push ybipin/prodtaskmaster:latest
    - name: Kubectl Action
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG_PROD }}
    - run: |
          kubectl apply -f deployment-service.yml
      

   
